### ISSUE TITLE
use a different port forwarder

### ISSUE THREAD

**Issue by UnluckySoviet** [MinorMole/RcloneLab#32]
As useful as serveo maybe, it suffers from frequent downtimes. It's down at the time of creating this issue...smh. We could look at possible alternatives such as:

- http://localhost.run/
- https://localtunnel.github.io/www/
- https://github.com/localtunnel/localtunnel

**Comment by MinorMole** [comment]
localhost.run have already in the code, but due to the [latest update](https://twitter.com/localhost_run/status/1161951567525961728) it can't use like Serveo.net anymore. It is the **Backup Website** button after you install qBittorrent, etc.

localtunnel looks interesting; I'll check it after I get better from sickness.

Thank you for your advice! 😁
