### ISSUE TITLE
Youtube-Dl unable to download Hotstar Videos

### ISSUE THREAD

**Issue by r-scott39** [MinorMole/RcloneLab#6]
Hey Minormole..!! Amazing script..! Just a tiny lil bug - Youtube-Dl at present in the script is able to download only Youtube videos and not Hotstar Videos (and maybe other sites too - hv to check).
Could you please make a slight update maybe to include all the 1000+ sites that is supposed to work with Youtube-Dl..?  
The list of supported sites - http://ytdl-org.github.io/youtube-dl/supportedsites.html

Also the max download speed while downloading playlists.... was limiting to around 25MB/s..!
keeps fluctuating between 5 to 25MB/s.. do have a look on that too..! 

Thanks.

**Comment by MinorMole** [comment]
It should work with all sites youtube-dl supported that didn't require login. I'll make login field later and many more options.

About the speed, it maxed out what youtube-dl can do (because of fragmentation). I still don't have an idea to implement a parallel downloading; for now, it only sequential download.

**Comment by MinorMole** [comment]
@r-scott39 YouTube-DL has been updated.

**Comment by MinorMole** [comment]
@all-contributors add MinorMole for projectManagement, maintenance, code
