### ISSUE TITLE
secure url

### ISSUE THREAD

**Issue by K-E-N-W-A-Y** [MinorMole/RcloneLab#8]
just add https instead of http for url generate section .so we can use SSL auto issued by let's encrypt for serveo,net or localhost.run. this is not an issue just a suggestion.

thanks in advance!

ex: 

image 01: 

![image](https://user-images.githubusercontent.com/25846872/61998797-16e1de00-b0d3-11e9-8ca0-42a84c51b30d.png)

image 02: 

![image](https://user-images.githubusercontent.com/25846872/61998803-23663680-b0d3-11e9-8c48-a2eabf94b6c7.png)

image 03: 

![image](https://user-images.githubusercontent.com/25846872/61998807-2b25db00-b0d3-11e9-880b-c27de43375a4.png)

**Comment by MinorMole** [comment]
The reason we did not use HTTPS as a default link because in Chrome (not sure about other browsers) if you enter qBittorrent WebUI the first time on serveo.net or localhost.run via HTTPS, it will cause **HTTP ERROR 401**.

The weirder is you can press F5 to fix it; the only solution is to hit the refresh button on the browser.

This will confuse the user and there nothing wrong with HTTP at this moment. Until it fixes, we still use HTTP as default.

<p align="center"><img height="300" src="https://i.imgur.com/8TRA0WA.png"></p>
